wandb_version: 1

method:
  desc: null
  value: random
metric:
  desc: null
  value:
    name: train_ari
    goal: maximize
parameters:
  desc: null
  value:
    lr:
      max: 0.1
      min: 1.0e-05
      distribution: log_uniform
    epochs:
      values:
      - 50
      - 60
      - 70
      - 80
      - 90
      - 100
      - 110
      - 120
      - 130
      - 140
      - 150
      - 160
      - 170
      - 180
      - 190
    new_adj_dim:
      values:
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
    pretrain_epochs:
      values:
      - 30
      - 40
      - 50
      - 60
      - 70
      - 80
      - 90
    numSampledCCs:
      values:
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
    numSampledCycles:
      values:
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1718938839
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 30
      - 49
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 11
      - 12
      - 30
      - 49
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.17.0
      6: 4.35.0
      8:
      - 2
      - 5
      13: linux-x86_64
